services:

  # Web server
  nginx:
    image: nginx:1.26
    ports:
      - '8080:8080'
    volumes:
      - ./_external/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/www/web-scrapper:ro
    depends_on:
      - php

  ###=============###
  ### API-BACKEND ###
  ###=============###

  # PHP Application
  php:
    build:
      dockerfile: Dockerfile-php
    expose:
      - 9000
    volumes:
      - ./:/www/web-scrapper
    depends_on:
      - db

  # MySQL Database
  db:
    image: mysql:8.4
    ports:
      - '3336:3336'
    environment:
      MYSQL_TCP_PORT: 3336
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web-scrap-db
    volumes:
      - ./.docker/mysql/local:/var/lib/mysql # This will store the DB data locally
