FROM php:8.3.7-fpm

## Install the PHP extensions we need
RUN apt-get update && apt-get install -y \
    curl \
    git \
    zip \
    unzip \
    libpq-dev \
    libzip-dev \
    supervisor \
    && pecl install xdebug \
    && docker-php-ext-configure pcntl --enable-pcntl \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install -j$(nproc) opcache pcntl pdo pdo_mysql sockets zip

# Configure Xdebug (adjust settings as needed)
RUN echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_port=9003" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.log=/tmp/xdebug.log" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# Install Composer v2.8.1
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.8.1

# Download and install Redis extension
RUN pecl install redis && docker-php-ext-enable redis

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory for the container
WORKDIR /www/web-scrapper

# Add entrypoint script to the container
COPY _external/entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod a+x /usr/bin/entrypoint.sh

# Add Supervisor configuration
COPY _external/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

ENTRYPOINT [ "entrypoint.sh" ]
